FROM node:20

WORKDIR /code

COPY package-lock.json package.json ./

RUN npm install
VOLUME /code/node_modules
COPY . .

RUN npx prisma generate

# ENV DATABASE_URL=mysql://root:daddyrozanc@mysql:3306/spzz

EXPOSE 3000

CMD ["npm", "run", "dev"]
