version: '3.8'

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql

  py-algorithms:
    build:
      context: ./py-algorithms
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    volumes:
      - ./py-algorithms:/code

  sveltekit:
    build: 
      context: ./sveltekit
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    volumes:
      - ./sveltekit:/app
      - /app/node_modules
    environment:
      NODE_ENV: development

volumes:
  mysql-data: