version: '3.8'

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql

  cv-parser:
    build:
      context: ./cv-parser
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    volumes:
      - ./cv-parser:/code
      - ./cv-parser/pdfs:/app/cv-parser/pdfs
      - shared-data:/app/cv-parser/pdfs:rw

  sveltekit:
    build: 
      context: ./sveltekit
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    volumes:
      - ./sveltekit:/app
      - /app/node_modules
    environment:
      NODE_ENV: development

  express:
    build:
      context: ./express
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./express:/app
      - /app/node_modules
      - shared-data:/app/cv-parser/pdfs:rw
    environment:
      NODE_ENV: development
    depends_on:
      mysql:
        condition: service_started

volumes:
  mysql-data:
  shared-data: