version: '3'
services:
  py-algorithms:
    build: .
    image: py-algorithms-image
    container_name: py-algorithms-container
    ports:
      - "5000:5000"
    volumes:
      - ./:/code
    restart: on-failure